moviemaven/urls.py
from django.contrib import admin
from django.urls import include, path
from movies.views import main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),  
    path('movies/', include('movies.urls')),
    path('', main, name='main'),
]

movies/urls.py
from django.urls import path
from . import views
app_name = 'movies' 
urlpatterns = [
    path('main', views.main, name='main'),
    path('movie_list', views.movie_list, name='movie-list'),
    path('movie/<int:movie_id>/', views.movie_detail, name='movie-detail'),
    path('recommendations/', views.movie_recommendations, name='recommendations'),
    path('recommendations/<int:num_recommendations>', views.movie_recommendations, name='recommendations'),
    path('add_to_watchlist/<int:movie_id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('add_to_watched/<int:movie_id>/', views.add_to_watched, name='add_to_watched'),
    path('randommovie/', views.random_movie, name='random_movie'),
    path('movie_details/<int:movie_id>/', views.movie_details, name='movie_details'),
    # path('get_movie_details/<int:movie_id>', views.get_movie_details, name = 'get_movie_details')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('select-genres/', views.select_genres, name='select_genres'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.user_profile, name='user_profile'),
    path('logout/', views.user_logout, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('move-to-watched/', views.move_to_watched, name='move_to_watched'),
]

movies/models.py
from django.db import models


class Movie(models.Model):
    """
    Django Movie Model
    """
    # IMDB id
    imdb_id = models.CharField(max_length=48, null=False)
    # Movie genres
    genres = models.CharField(max_length=200, null=True)
    # Original language
    original_language = models.CharField(max_length=20, null=True)
    # Original movie title
    original_title = models.CharField(max_length=500, null=False)
    # Movie release date
    release_date = models.IntegerField(default=1970)
    # Movie overview
    overview = models.TextField(max_length=2000, null=True)
    # Average voting for the movie
    vote_average = models.FloatField(default=0)
    # Total votes for ths movie
    vote_count = models.IntegerField(default=0)
    # The movie's poster path
    poster_path = models.CharField(max_length=64, null=True)


    def __str__(self):
        return self.original_title

movies/views.py
from functools import reduce
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie
from django.db.models import Count, Q, F,Count, Case, When
from django.contrib.auth.decorators import login_required
from users.models import WatchedMovie, Watchlist, Genre
from django.contrib import messages
from django.db.models import Case, When

from operator import or_




from django.http import JsonResponse

# @login_required
# def get_movie_details(request, movie_id):
#     movie = Movie.objects.get(pk=movie_id)
#     context = {'movie': movie}
#     return render(request, 'movies/movie_details_partial.html', context)


def main(request):
    return render(request, 'movies/main.html')



def movie_list(request):
    movies = Movie.objects.all()
    watched_movie_ids = WatchedMovie.objects.filter(user=request.user).values_list('movie_id', flat=True)
    watchlist_movie_ids = Watchlist.objects.filter(user=request.user).values_list('movie_id', flat=True)

    watched_movies = []
    watchlist_movies = []

    for movie in movies:
        if movie.id in watched_movie_ids:
            watched_movies.append(movie)
        elif movie.id in watchlist_movie_ids:
            watchlist_movies.append(movie)

    print(watched_movie_ids)  # Debugging statement
    print(watchlist_movie_ids) 
    context = {
        'movies': movies,
        'watched_movies': watched_movies,
        'watchlist_movies': watchlist_movies,
    }

    return render(request, 'movies/movie_list.html', context)


def movie_detail(request, movie_id):
    
    movie = Movie.objects.get(pk=movie_id)
   
    watchlist_movies = Watchlist.objects.filter(user=request.user)
    watched_movies = WatchedMovie.objects.filter(user=request.user)
    watched_movie_ids = WatchedMovie.objects.filter(user=request.user).values_list('movie_id', flat=True)
    watchlist_movie_ids = Watchlist.objects.filter(user=request.user).values_list('movie_id', flat=True)


    context = {
        
    'movie': movie,
    'watchlist_movies': watchlist_movies,
    'watched_movies': watched_movies,
    'watchlist_movie_ids': watchlist_movie_ids,
    'watched_movie_ids': watched_movie_ids,
    }



    # Render a template with movie details
    return render(request, 'movies/movie_detail.html', context)






def movie_details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    watchlist_movies = Watchlist.objects.filter(user=request.user, movie=movie)
    watched_movies = WatchedMovie.objects.filter(user=request.user, movie=movie)

    context = {
        'movie': movie,
        'watchlist_movies': watchlist_movies,
        'watched_movies': watched_movies,
    }

    return render(request, 'movies/movie_details.html', context)



@login_required
def movie_recommendations(request, num_recommendations=10):
    
    


    selected_genres = request.session.get('selected_genres', [])
    if selected_genres:
        selected_genre_names = Genre.objects.filter(id__in=selected_genres).values_list('name', flat=True)
        q_objects = [Q(genres__icontains=f" {genre} ") | Q(genres__istartswith=f"{genre} ") | Q(genres__iendswith=f" {genre}") | Q(genres__exact=genre) for genre in selected_genre_names]
    else:
        q_objects = []
    # Get a list of watched and watchlisted movie IDs
    watched_movie_ids = WatchedMovie.objects.filter(user=request.user).values_list('movie_id', flat=True)
    watchlist_movie_ids = Watchlist.objects.filter(user=request.user).values_list('movie_id', flat=True)



    
    # Get recommended movies that contain any of the selected genres and haven't been watched or watchlisted yet
    
    recommended_movies = Movie.objects.filter(
        reduce(or_, q_objects)
    ).exclude(id__in=watched_movie_ids).exclude(id__in=watchlist_movie_ids)

    # Annotate with the count of matched selected genres
    recommended_movies = recommended_movies.annotate(
        num_matched_selected_genres=Count(Case(*[When(genres__icontains=f" {genre} ", then=1) for genre in selected_genre_names]))
    )

    # Sort movies by the number of matched selected genres in descending order, then by vote_average
    recommended_movies = recommended_movies.order_by(
        '-num_matched_selected_genres',
        '-vote_average'
    )[:num_recommendations]

    for movie in recommended_movies:
        print(f"Movie Title: {movie.original_title}")
        print(f"Matched Selected Genres: {movie.num_matched_selected_genres}")
        print(f"Movie id: {movie.imdb_id}")

    # # Fetch the user's watchlist and watched movies
    # watchlist_movies = Watchlist.objects.filter(user=request.user, movie__in=recommended_movies).values_list('movie_id', flat=True)
    # watched_movies = WatchedMovie.objects.filter(user=request.user, movie__in=recommended_movies).values_list('movie_id', flat=True)
    watchlist_movies = Watchlist.objects.filter(user=request.user, movie__in=recommended_movies)
    watched_movies = WatchedMovie.objects.filter(user=request.user, movie__in=recommended_movies)


    context = {
        'genres': selected_genre_names,
        'recommended_movies': recommended_movies,
        'watchlist_movies': watchlist_movies,
        'watched_movies': watched_movies,
        
    }
   
    if request.method == 'POST':
        movie_id = request.POST.get('movie_id')
        action = request.POST.get('action')

        if movie_id and action:
            try:
                movie = Movie.objects.get(id=movie_id)
                if action == 'watchlist':
                    Watchlist.objects.get_or_create(user=request.user, movie=movie)
                    # Remove the movie from recommended movies
                    recommended_movies = recommended_movies.exclude(id=movie_id)
                    messages.success(request, f'{movie.original_title} has been added to your watchlist!')
                elif action == 'watched':
                    rating = request.POST.get('rating')
                    if not rating:
                        messages.error(request, 'Please provide a rating before adding to watched.')
                    else:
                        WatchedMovie.objects.get_or_create(user=request.user, movie=movie, rating=rating)
                        # Remove the movie from recommended movies
                        recommended_movies = recommended_movies.exclude(id=movie_id)
                        messages.success(request, f'{movie.original_title} has been added to your watched list!')
            except Movie.DoesNotExist:
                pass

    context['recommended_movies'] = recommended_movies

    # Return the context or render a template with the context
    return render(request, 'movies/recommendations.html', context)

from random import choice

@login_required
def random_movie(request):
    # Get the user's watched and watchlist movies
    watched_movies = WatchedMovie.objects.filter(user=request.user).values_list('movie', flat=True)
    watchlist_movies = Watchlist.objects.filter(user=request.user).values_list('movie', flat=True)
   
    watched_movie_ids = WatchedMovie.objects.filter(user=request.user).values_list('movie_id', flat=True)
    watchlist_movie_ids = Watchlist.objects.filter(user=request.user).values_list('movie_id', flat=True)
    
    # Get a random movie that the user hasn't watched or added to the watchlist
    random_movie = Movie.objects.exclude(id__in=watched_movies).exclude(id__in=watchlist_movies).order_by('?').first()

    context = {
        'random_movie': random_movie,
        'watchlist_movies': watchlist_movies,
        'watched_movies': watched_movies,
        'watchlist_movie_ids': watchlist_movie_ids,
        'watched_movie_ids': watched_movie_ids,
    }

    return render(request, 'movies/random_movie.html', context)






@login_required
def add_to_watchlist(request, movie_id):
    # Get the Movie object with the given `movie_id`
    movie = get_object_or_404(Movie, pk=movie_id)

    # Check if the user already has this movie in their watchlist
    if Watchlist.objects.filter(user=request.user, movie=movie).exists():
        messages.info(request, 'Movie is already in your watchlist.')
    else:
        # Add the movie to the user's watchlist
        Watchlist.objects.create(user=request.user, movie=movie)
        messages.success(request, 'Movie added to your watchlist successfully.')


    return redirect(request.META.get('HTTP_REFERER', 'movies:random-movie'))






@login_required
def add_to_watched(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)

    if request.method == 'POST':
        rating = request.POST.get('rating')
        watched_movie, created = WatchedMovie.objects.get_or_create(user=request.user, movie=movie, defaults={'rating': rating})
        if not created:
            watched_movie.rating = rating
            watched_movie.save()

        # Check if the movie exists in the user's watchlist
        watchlist_movie = Watchlist.objects.filter(user=request.user, movie_id=movie_id).first()
        if watchlist_movie:
            watchlist_movie.delete()

    # Redirect to the previous page after performing the action
    return redirect(request.META.get('HTTP_REFERER', 'movies:movie-list'))

movies/templates/movies/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to Movie Maven</title>
    <link rel="stylesheet" type="text/css" href="{% static 'movies/main.css' %}">
    <link rel="icon" href="{% static 'users/logo.png' %}"  type="image/png">
</head>
<body>
    <header>
        <div class="logo">
            <a href="{% url 'movies:movie-list' %}"></a>
            <img src="{% static 'movies/logo.png' %}" alt="Movie Maven Logo">
        </div>
        <h1>Welcome to Movie Maven</h1>
        <p>Where the reel magic begins and the popcorn never ends!</p>
    </header>
    <main>
        
        <p>Join us and discover a world of movies.</p>
        <div class="buttons">
            <a href="{% url 'users:register' %}">
                <button>Register</button>
            </a>
            <p class="small-text">Already a member? <a href="{% url 'users:login' %}">Login</a></p>
        </div>
    </main>
</body>
</html>

movies/templates/movies/movie_detail.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'movies/m_d.css' %}">
    <div class="movie-details">
        <div class="movie-poster">
            <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt="{{ movie.original_title }} Poster" width="320" height="480" onerror="this.onerror=null; this.src='/' + 'static' + '/movies/alternate.png';">
        </div>
        <div class="movie-info">
            <h1>{{ movie.original_title }}</h1>
            
            <p class="genres"><strong>Genres:</strong> {{ movie.genres }}</p>
            <p class="release-date"><strong>Release Date:</strong> Date: {{ movie.release_date }}</p>
            <p class="rating"><strong>Rating:</strong> {{ movie.vote_average }} ⭐</p>
            <p class="overview"><strong>Overview:</strong> {{ movie.overview }}</p>
            
            
            <div class="watchlist-section">
                {% if request.user.is_authenticated %}
                {% if movie.id in watched_movie_ids %}
                    <p class="watched">(Already Watched! 👍)</p>
                {% elif movie.id in watchlist_movie_ids %}
                    <p class="watchlist">(Already in your Watchlist 🙃)</p>
                    <form method="post" action="{% url 'movies:add_to_watched' movie.id %}">
                        {% csrf_token %}
                        <label for="rating">Rating (out of 10):</label>
                        <input type="number" name="rating" id="rating" min="1" max="10" required>
                        <button type="submit">Add to Watched</button>
                    </form>
                {% else %}
                    <form method="post" action="{% url 'movies:add_to_watchlist' movie.id %}">
                        {% csrf_token %}
                        <button type="submit" class="add-to-watchlist">Add to Watchlist</button>
                    </form>
                    <form method="post" action="{% url 'movies:add_to_watched' movie.id %}">
                        {% csrf_token %}
                        <label for="rating">Rating (out of 10):</label>
                        <input type="number" name="rating" id="rating" min="1" max="10" required>
                        <button type="submit">Add to Watched</button>
                    </form>
                {% endif %}
            {% else %}
                <p class="login-required">Please <a href="{% url 'account_login' %}?next={{ request.path }}">log in</a> to add to your watched list or watchlist.</p>
            {% endif %}
            
                
            </div>
        </div>
    </div>
    <a href="{% url 'movies:movie-list' %}" class="back-to-movie-list">Back to Movie List</a>
    <a href="{% url 'users:select_genres' %}" class="back-to-movie-list">Explore Genres?!</a>
{% endblock %}

movies/templates/movies/movie_details.html
<!-- movie_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ movie.original_title }} Details</title>
</head>
<body>
    <h2>{{ movie.original_title }} Details</h2>
    
    <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt="{{ movie.original_title }} Poster Poster" width="320" height="480">
    <p>Genres: {{ movie.genres }}</p>
    <p>Release Date: {{ movie.release_date }}</p>
    <p>Overview: {{ movie.overview }}</p>
  
    {% if user.is_authenticated %}
                    {% if movie in watchlist_movies %}
                        <p>In Your Watchlist</p>
                    {% else %}
                        <form method="post" action="{% url 'movies:add_to_watchlist' movie.id %}">
                            {% csrf_token %}
                            <button type="submit">Add to Watchlist</button>
                        </form>
                    {% endif %}
                    {% if movie in watched_movies %}
                        <p>Already Watched</p>
                    {% else %}
                        <form method="post" action="{% url 'movies:add_to_watched' movie.id %}">
                            {% csrf_token %}
                            <label for="rating">Rating (out of 10):</label>
                            <input type="number" name="rating" id="rating" min="1" max="10" required>
                            <button type="submit">Add to Watched</button>
                        </form>
                    {% endif %}
                {% endif %}
</body>
</html> -->

<!-- {% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ movie.original_title }} Details</title>
    <link rel="stylesheet" href="{% static 'movies/movie_details.css' %}">
</head>
<body>
    <h2>{{ movie.original_title }} Details</h2>
    <div class="movie-details-container">
        
        <div class="movie-poster">
            <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt="{{ movie.original_title }} Poster" width="320" height="480">
        </div>
        
        <div class="movie-details">
            <p>Genres: {{ movie.genres }}</p>
            <p>Release Date: {{ movie.release_date }}</p>
            <p>Overview: {{ movie.overview }}</p>
           
            {% if user.is_authenticated %}
                {% if movie in watchlist_movies %}
                    <p>In Your Watchlist</p>
                {% else %}
                    <form method="post" action="{% url 'movies:add_to_watchlist' movie.id %}">
                        {% csrf_token %}
                        <button type="submit">Add to Watchlist</button>
                    </form>
                {% endif %}
                {% if movie in watched_movies %}
                    <p>Already Watched</p>
                {% else %}
                    <form method="post" action="{% url 'movies:add_to_watched' movie.id %}">
                        {% csrf_token %}
                        <label for="rating">Rating (out of 10):</label>
                        <input type="number" name="rating" id="rating" min="1" max="10" required>
                        <button type="submit">Add to Watched</button>
                    </form>
                {% endif %}
            {% endif %}
        </div>
    </div>
</body>
</html> -->
<!-- movie_details.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ movie.original_title }} Details</title>
    <link rel="stylesheet" href="{% static 'movies/movie_details.css' %}">
</head>
<body>
    <style>
        form input {
  display: inline-block;
  width: 60px;
  vertical-align: top; /* add this line */
}

form button {
  display: inline-block;
  margin-left: 10px;
}
    </style>
    <div class="container">
        <h2>{{ movie.original_title }}</h2>
        <div class="movie-details-container">
            <!-- Movie poster on the left -->
            <div class="movie-poster">
                <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt="{{ movie.original_title }} Poster" width="320" height="480" onerror="this.onerror=null; this.src='/' + 'static' + '/movies/alternate.png';">
            </div>
            <!-- Movie details on the right -->
            <div class="movie-details">
                <p><strong>Genres:</strong> {{ movie.genres }}</p>
                <p><strong>Release Date:</strong> {{ movie.release_date }}</p>
                <p><strong>Rating:</strong> {{ movie.vote_average}}⭐</p>
                <p><strong>Overview:</strong> {{ movie.overview }}</p>
                <!-- Include watchlist and watched functionality if needed -->
                {% if user.is_authenticated %}
                    {% if movie in watchlist_movies %}
                        <p class="watchlist">In Your Watchlist</p>
                    {% else %}
                        <form method="post" action="{% url 'movies:add_to_watchlist' movie.id %}">
                            {% csrf_token %}
                            <button type="submit">Add to Watchlist</button>
                        </form>
                    {% endif %}
                    {% if movie in watched_movies %}
                        <p class="watched">Already Watched</p>
                    {% else %}
                        <form method="post" action="{% url 'movies:add_to_watched' movie.id %}">
                            {% csrf_token %}
                            <label for="rating">Rating (out of 10):</label>
                            <input type="number" name="rating" id="rating" min="1" max="10" required>
                            <button type="submit">Add to Watched</button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>

movies/templates/movies/movie_details_partial.html
<p>Original Title: {{ movie.original_title }}</p>
<p>Genres:
    {% for genre in movie.genres|split_string:" " %}
        {{ genre }}
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p>Release Date: {{ movie.release_date }}</p>
<p>Overview: {{ movie.overview }}</p>

movies/templates/movies/movie_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Movie List</title>
    <link rel="stylesheet" href="{% static 'movies/movie_list.css' %}">
    <link rel="icon" href="{% static 'users/logo.png' %}"  type="image/png">
</head>
<body>
    <div class="container">
        <h1>Welcome to our treasure trove of cinematic gems.✨</h1>
        <p class="subtitle">You've unlocked our inventory – the entire list of movies is now at your fingertips for your exploration. Enjoy your cinematic journey!</p>
        <ul class="movie-list">
            {% for movie in movies %}
            <li class="movie-card">
                <a href="{% url 'movies:movie-detail' movie.id %}">
                    {% if movie.id in watched_movie_ids %}
                        <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="{{ movie.original_title }} Poster" class="watched-poster">
                        <span class="tag watched-tag">Watched</span>
                    {% elif movie.id in watchlist_movie_ids %}
                        <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="{{ movie.original_title }} Poster" class="watchlist-poster">
                        <span class="tag watchlist-tag">Watchlist</span>
                    {% else %}
                        <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="{{ movie.original_title }} Poster">
                    {% endif %}
                </a>
                <div class="movie-details">
                    <p class="movie-title">{{ movie.original_title }}</p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

movies/templates/movies/random_movie.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'movies/rm_styles.css' %}">
    <title>Random Movie Recommendation</title>
</head>
<body>
    <h2 align="centre" >Your Mystery Movie Mixtape 🎥🔮</h2>
    {% if random_movie %}
    <div class="movie-container">
        <div class="movie-poster">
            <img src="https://image.tmdb.org/t/p/original/{{ random_movie.poster_path }}" alt="{{ random_movie.original_title }} Poster" width="320" height="480" data-movie-id="{{ movie.id }}" onerror="this.onerror=null; this.src='/' + 'static' + '/movies/alternate.png';">
        
        <!-- <img src="https://image.tmdb.org/t/p/original//iE63xgOl9hCkr5aN3Bq2dk7iPpu.jpg" > -->
        </div>
        <div class="movie-details">

            <h2>{{ random_movie.original_title }}</h2>
                <p><strong>Genres:</strong> {{ random_movie.genres }}</p>
                <p><strong>Release Date:</strong> {{ random_movie.release_date }}</p>
                <p><strong>Rating:</strong> {{ random_movie.vote_average}}⭐</p>
                <p><strong>Overview:</strong> {{ random_movie.overview }}</p>
                <!-- Include watchlist and watched functionality if needed -->
                {% if user.is_authenticated %}
                    {% if movie in watchlist_movies %}
                        <p class="watchlist">In Your Watchlist</p>
                    {% else %}
                        <form method="post" action="{% url 'movies:add_to_watchlist' random_movie.id %}">
                            {% csrf_token %}
                            <button type="submit">Add to Watchlist</button>
                        </form>
                    {% endif %}
                    {% if movie in watched_movies %}
                        <p class="watched">Already Watched</p>
                    {% else %}
                        <form method="post" action="{% url 'movies:add_to_watched' random_movie.id %}">
                            {% csrf_token %}
                            <label for="rating">Rating:</label>
                            <input type="number" name="rating" id="rating" min="1" max="10" required>
                            <button type="submit">Add to Watched</button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
    </div>
  
    {% else %}
        <p>No more random movies available.</p>
    {% endif %}
    <div class = "buttons">
        <a href="{% url 'movies:random_movie' %}" class="btn btn-primary">Generate Another Random Movie</a>
        <a href="{% url 'users:select_genres' %}" class="btn btn-secondary">Back to Genre Selection</a>
    </div>
</body>
{%endblock%}

movies/templates/movies/recommendations.html
{% extends "users/base.html" %}
{% load static %}


{% block content %}
    <title>Movie Recommendations</title>
    <link rel="stylesheet" type="text/css" href="{% static 'movies/recommendations.css' %}">
  

    <h3>Drumroll, please! 🥁 Your moment of cinematic truth has arrived. 🎬</h3>
    <div class="movie-grid">
        {% for movie in recommended_movies %}
            <div class="movie-poster">
                
                <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt="{{ movie.original_title }} Poster" width="320" height="480" data-movie-id="{{ movie.id }}" onerror="this.onerror=null; this.src='/' + 'static' + '/movies/alternate.png';">


            </div>
        {% endfor %}
    </div>

    <div id="movie-details-overlay">
        <div class="movie-details-content">
            <div class="movie-poster-container">
               
            </div>
            <!-- Movie details content will be loaded here dynamically -->
            
        </div>
    </div>
    
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'movies/recommendations.js' %}"></script>

{% endblock %}