moviemaven/urls.py
from django.contrib import admin
from django.urls import include, path
from movies.views import main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),  
    path('movies/', include('movies.urls')),
    path('', main, name='main'),
]

movies/urls.py
from django.urls import path
from . import views
app_name = 'movies' 
urlpatterns = [
    path('main', views.main, name='main'),
    path('movie_list', views.movie_list, name='movie-list'),
    path('movie/<int:movie_id>/', views.movie_detail, name='movie-detail'),
    path('recommendations/', views.movie_recommendations, name='recommendations'),
    path('recommendations/<int:num_recommendations>', views.movie_recommendations, name='recommendations'),
    path('add_to_watchlist/<int:movie_id>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('add_to_watched/<int:movie_id>/', views.add_to_watched, name='add_to_watched'),
    path('randommovie/', views.random_movie, name='random_movie'),
    path('movie_details/<int:movie_id>/', views.movie_details, name='movie_details'),
    # path('get_movie_details/<int:movie_id>', views.get_movie_details, name = 'get_movie_details')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('select-genres/', views.select_genres, name='select_genres'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.user_profile, name='user_profile'),
    path('logout/', views.user_logout, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('move-to-watched/', views.move_to_watched, name='move_to_watched'),
]

users/models.py
# users/models.py
from django.db import models
from django.contrib.auth.models import User
from movies.models import Movie

class Genre(models.Model):
    name = models.CharField(max_length=25)


    def __str__(self):
        return self.name


# List of genres
genre_names = [
    "Western", "Thriller", "Science Fiction", "Music", "Romance",
    "Horror", "History", "War", "Drama", "Foreign",
    "Comedy", "Adventure", "Documentary", "Crime", "Animation",
    "Family", "Action", "Fantasy", "Mystery", "TV", "Movie"
]

# Create instances of Genre for each genre if they don't exist
for genre_name in genre_names:
    Genre.objects.get_or_create(name=genre_name)



class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)

class WatchedMovie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User  # Add this import
# from django.contrib.auth.password_validation import MinimumLengthValidator
# from django.contrib.auth.password_validation import MinimumLengthValidator, CommonPasswordValidator, NumericPasswordValidator

import re




# from django.contrib.auth import get_user_model

# from django.contrib.auth import password_validation
# from django.contrib.auth.password_validation import MinimumLengthValidator, CommonPasswordValidator, NumericPasswordValidator

# class CustomRegistrationForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
    
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['password1'].validators.append(MinimumLengthValidator(8))
#         self.fields['password1'].validators.append(CommonPasswordValidator())
#         self.fields['password1'].validators.append(NumericPasswordValidator())


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']



class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
  

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

users/views.py
# users/views.py
import logging
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse,JsonResponse
from django.urls import reverse
from .forms import CustomRegistrationForm, LoginForm
from .forms import EditProfileForm  
from movies.models import Movie
from django.contrib.auth.models import User
from .models import Genre, WatchedMovie, Watchlist
from django.contrib import messages
from collections import Counter

from django.views.decorators.http import require_POST



def register(request):
    if request.method == 'POST':
        form = CustomRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('users:select_genres')
    else:
        form = CustomRegistrationForm()

    return render(request, 'users/register.html', {'form': form})





def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Check if the user exists
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                return render(request, 'users/login.html', {'form': form, 'error_message': 'Invalid username or password.'})

            # Authenticate the user
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('users:select_genres')
            else:
                return render(request, 'users/login.html', {'form': form, 'error_message': 'Invalid username or password.'})
    else:
        form = LoginForm()

    return render(request, 'users/login.html', {'form': form})


@login_required
def select_genres(request):
    genres = Genre.objects.all()

    if request.method == 'POST':
        if 'random_movie' in request.POST:
            return redirect('movies:random_movie')

        selected_genres = request.POST.getlist('genres[]')
        num_recommendations = int(request.POST.get('num_recommendations', 10))
        print(selected_genres, num_recommendations)
        if not selected_genres:  # Check if no genres are selected
            error_msg = 'Please select at least one genre.'
            return render(request, 'users/select_genres.html', {'genres': genres, 'error_msg': error_msg})
        request.session['selected_genres'] = selected_genres
        return redirect('movies:recommendations', num_recommendations=num_recommendations)
   


    return render(request, 'users/select_genres.html', {'genres': genres})


@login_required
def user_profile(request):
    user = request.user
    watchlist_movies1= Watchlist.objects.filter(user=request.user).select_related('movie')
    watched_movies1 = WatchedMovie.objects.filter(user=request.user).select_related('movie')

    # Fetch the user's watched and watchlisted movies
    watchlist_movies = Watchlist.objects.filter(user=user).values_list('movie_id', flat=True)
    watched_movies = WatchedMovie.objects.filter(user=user).values_list('movie_id', flat=True)

    # Combine the movie IDs from both watchlist and watched movies
    user_movie_ids = set(list(watchlist_movies) + list(watched_movies))

    # Fetch the movies corresponding to the combined IDs
    user_movies = Movie.objects.filter(pk__in=user_movie_ids)

    # Extract genre information from the user's movies
    user_genres = []
    for movie in user_movies:
        if movie.genres:
            user_genres.extend(movie.genres.split())

    # Count genre occurrences
    genre_counts = Counter(user_genres)

    # Sort genres by count in descending order
    favorite_genres = [genre for genre, _ in genre_counts.most_common(3)]  # Change '3' to the desired number of favorite genres

    context = {
        'user': user,
        'watchlist_movies': watchlist_movies,
        'watched_movies': watched_movies,
        'watchlist_movies1': watchlist_movies1,
        'watched_movies1': watched_movies1,
        'favorite_genres': favorite_genres,
    }

    return render(request, 'users/profile.html', context)



@login_required
def user_logout(request):
    logout(request)
    return redirect('movies:main')








@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            new_username = form.cleaned_data['username']
            if new_username != request.user.username and User.objects.filter(username=new_username).exists():
                messages.warning(request, 'Username already exists. Please choose a different one.')
            else:
                form.save()
                messages.success(request, 'Your profile has been updated.')  # Add a success message

                # Handle watched movies
                watched_movies = request.POST.getlist('watched_movies[]')
                ratings = request.POST.getlist('ratings[]')
                for i, movie_id in enumerate(watched_movies):
                    rating = ratings[i]
                    if rating:
                        WatchedMovie.objects.create(user=request.user, movie_id=movie_id, rating=rating)
                    else:
                        WatchedMovie.objects.create(user=request.user, movie_id=movie_id)

                # Handle unwatched movies
                unwatched_movies = Watchlist.objects.filter(user=request.user).exclude(id__in=watched_movies)
                unwatched_movies.delete()

                return redirect('users:user_profile')  # Redirect to the profile page
        else:
            messages.error(request, 'Your input is invalid.')  # Add an error message if the form is invalid

    else:
        form = EditProfileForm(instance=request.user)

    # Fetch movies from your database for the search bar
    query = request.GET.get('q')
    if query:
        movies = Movie.objects.filter(original_title__icontains=query)
    else:
        movies = Movie.objects.none()

    watchlist_movies = Watchlist.objects.filter(user=request.user)
    watched_movies = WatchedMovie.objects.filter(user=request.user).select_related('movie')  # Include the movie details

    context = {
        'form': form,
        'movies': movies,
        'watchlist_movies': watchlist_movies,
        'watched_movies': watched_movies,
    }

    return render(request, 'users/edit_profile.html', context)

@require_POST
@login_required
def move_to_watched(request):
    movie_id = request.POST.get('movie_id')
    rating = request.POST.get('rating')
    movie = Movie.objects.get(id=movie_id)

    if rating:
        watched_movie, created = WatchedMovie.objects.get_or_create(user=request.user, movie=movie)
        watched_movie.rating = rating
        watched_movie.save()

        # Delete the movie from the watchlist
        Watchlist.objects.filter(movie=movie, user=request.user).delete()

        response_data = {
            'success': True,
            'movie_title': movie.original_title,
        }
        return JsonResponse(response_data)
    else:
        response_data = {
            'success': False,
            'message': 'Please enter a valid rating.',
        }
        return JsonResponse(response_data)

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'users/base.css' %}">
        
        <link rel="icon" href="{% static 'users/logo.png' %}"  type="image/png">

        <style>
            body {
                background-color: #88b3c2;
                font-family: Arial, sans-serif;
                font-size: 16px;
                line-height: 1.5;
                margin: 0;
                padding: 0;
            }
            header {
                background-color: #083057;
                color: #FFFFFF;
                display: flex;
                justify-content: space-between;
                align-items: center;
                padding: 10px;
            }
            header img {
                width: 100px;
            }
            .navbar-links {
                display: flex;
                justify-content: flex-end;
            }
            .navbar-links a:not(:last-child) {
                margin-right: 20px;
            }
            .button {
                display: inline-block;
                padding: 8px 16px;
                font-size: 16px;
                font-weight: bold;
                text-align: center;
                text-decoration: none;
                background-color: #4CAF50;
                color: #FFFFFF;
                border-radius: 8px;
                transition: background-color 0.3s ease;
            }
            .button:hover {
                background-color: #3e8e41;
            }
            footer {
                width: 100%;
                text-align: center;
                padding: 20px;
                background-color: #083057;
                color: #FFFFFF;
            }
            footer img {
                width: 100%;
                height: auto;
            }
            #content {
                padding: 20px;
            }
        </style>
    </head>
    <body>
        <header>
            <a href="{% url 'movies:movie-list' %}">
                <img src="{% static 'users/logo.png' %}" alt="Your Logo">
            </a>
            <div class="navbar">
                <div class="navbar-links">
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:user_profile' %}" class="button">User</a>
                    <a href="{% url 'users:logout' %}" class="button">Logout</a>
                    {% endif %}
                </div>
            </div>
        </header>
        
        
        <div id="content">
            {% block content %}{% endblock %}
        </div>

        <footer>
            <img src="https://styles.redditmedia.com/t5_2qh3s/styles/bannerBackgroundImage_k1ukyjei82r81.png" alt="Footer Image">
        </footer>
        
    </body>
</html>

users/templates/users/edit_profile.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
    <title>Edit Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'users/edit_profile.css' %}">
</head>
<body>
    <h1>Edit Profile</h1>
    
    <form method="post" action="{% url 'users:edit_profile' %}">
        {% csrf_token %}
        
        <div>
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
      
        <div>
            {{ form.first_name.label_tag }}
            {{ form.first_name }}
        </div>
        
       
        <div>
            {{ form.last_name.label_tag }}
            {{ form.last_name }}
        </div>
        
        <h3>Watchlist</h3>
<ul>
    <!-- {% for watchlistmovie in watchlist_movies %}
        <li>
            {{ watchlistmovie.movie.original_title }}
        </li>
    {% empty %}
        <p>No movies in your watchlist.</p>
    {% endfor %} -->
    {% for watchlistmovie in watchlist_movies %}
    <li>
        <a href="{% url 'movies:movie-detail' watchlistmovie.movie.id %}">{{ watchlistmovie.movie.original_title }}</a>

       
    </li>
{% empty %}
    <p>No movies in your watchlist.</p>
{% endfor %}

</ul>

<h3>Watched Movies</h3>
<ul>
    {% for watched_movie in watched_movies %}
        <li>
            {{ watched_movie.movie.original_title }}
        </li>
    {% empty %}
        <p>No watched movies.</p>
    {% endfor %}
</ul>



        <button type="submit">Save Changes</button>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

   
</body> 
{% endblock %}

users/templates/users/index.html
<html>
    <head>
        <title>index</title>

    </head>
    <body>
        <h3>welcome</h3>
        {% for message in messages %}
        <div class ="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            <strong> Message:</strong>{{message}}
        </div>
        {%endfor%}
        {% if user.is_authenticated %}
        <h3>Hello {{fname}}</h3>
        <button type="submit"><a href="/users/register" > Register</a></button>
        {%else%}
        <button type="submit"><a href="/login" >Login</a></button>
        <button type="submit"><a href="/logout" >Logout</a></button>
        {%endif%}
    </body>
</html>

users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'users/login.css' %}">
    <link rel="icon" href="{% static 'users/logo.png' %}"  type="image/png">
    
</head>
<body>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: url("https://i.pinimg.com/originals/a8/ec/06/a8ec0697a5399d67899078d2632e1b75.png");
            background-size: cover;
            background-position: right center;
            background-attachment: fixed;
        }

        body::before {
            content: "";
            background-color: rgba(255, 255, 255, 0.205);
            position: fixed;
            top: 0;
            left: 0;
            width: auto;
            height: auto;
            z-index: -1;
        }

        /* Rest of your CSS styles for header, logo, main content, etc. */

    </style>
    <div class="container">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>

        {% if error_message %}
            <div class="error">{{ error_message }}</div>
        {% endif %}

        <p>Don't have an account? <a href="{% url 'users:register' %}">Register</a></p>
    </div>
</body>
</html> 

users/templates/users/profile.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
    <title>User Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'users/profile.css' %}">
    <div class="container">
        <h2 class="profile-heading">User Profile: {{ user.username }}</h2>

        <div class="box-container">
            <div class="box">
                <h3 class="box-heading">Watched Movies</h3>
                <ul>
                    {% for watched_movie in watched_movies1 %}
                        <li>
                            {{ watched_movie.movie.original_title }}
                            <span class="rating">({{ watched_movie.rating }} ⭐)</span>
                        </li>
                    {% empty %}
                        <p class="empty-message">No watched movies.</p>
                    {% endfor %}
                </ul>
            </div>

            <div class="box">
                <h3 class="box-heading">Watchlist</h3>
                <ul>
                    {% for watchlistmovie in watchlist_movies1 %}
                        <li>
                            <span class="movie-title">{{ watchlistmovie.movie.original_title }}</span>
                        </li>
                    {% empty %}
                        <p class="empty-message">No movies in your watchlist.</p>
                    {% endfor %}
                </ul>
            </div>

            <div class="box">
                <h3 class="box-heading">Your Top Genres</h3>
                <ul class="favorite-genres">
                    {% for genre in favorite_genres %}
                        <li>{{ genre }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="butn">
            <a href="{% url 'users:edit_profile' %}" class="btn edit-profile-btn">Edit Profile</a>
            <a href="{% url 'users:select_genres' %}" class="btn genres-btn">Back to Genres</a>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Registration</title>
    <link rel="stylesheet" type="text/css" href="{% static 'users/register.css' %}">
    <link rel="icon" href="{% static 'users/logo.png' %}"  type="image/png">
</head>
    
<body>
    
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: url("https://i.pinimg.com/originals/a8/ec/06/a8ec0697a5399d67899078d2632e1b75.png");
            background-size: cover;
            background-position: right center;
            background-attachment: fixed;
        }

        body::before {
            content: "";
            background-color: rgba(255, 255, 255, 0.205);
            position: fixed;
            top: 0;
            left: 0;
            width: auto;
            height: auto;
            z-index: -1;
        }

        /* Rest of your CSS styles for header, logo, main content, etc. */

    </style>
    <div class="form-container">
        <form method="post">
            {% csrf_token %}
           
           
            <div class="form-field">
                <label for="{{ form.username.id_for_label }}">Username:</label>
                {{ form.username }}
            </div>
            <div class="form-field">
                <label for="{{ form.email.id_for_label }}">Email:</label>
                {{ form.email }}
            </div>
            <div class="form-field">
                <label for="{{ form.first_name.id_for_label }}">First name:</label>
                {{ form.first_name }}
            </div>
            <div class="form-field">
                <label for="{{ form.last_name.id_for_label }}">Last name:</label>
                {{ form.last_name }}
            </div>
            <div class="form-field">
                <label for="{{ form.password1.id_for_label }}">Password:</label>
                {{ form.password1 }}
                <div class="password-requirements">
                    <p>Password must contain at least 8 characters and be alphanumeric.</p>
                </div>
            </div>
            <div class="form-field">
                <label for="{{ form.password2.id_for_label }}">Password confirmation:</label>
                {{ form.password2 }}
            </div>
            <button type="submit">Register</button>


            {% if form.errors %}
                <ul class="errorlist">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
        </form>
    </div>
</body>
</html>

users/templates/users/select_genres.html
{% extends "users/base.html" %}
{% load static %}



{% block content %}
    <title>Genre Selection</title>
    <link rel="stylesheet" type="text/css" href="{% static 'users/sg_styles.css' %}">
    <h3>Choose Your Movie Magic! 🍿✨</h3>
    <p>Westerns or Whodunits, Sci-Fi or Swoon-worthy Romance, our Genres are your gateway to film enchantment. Click and let the movie marathon begin!</p>
    <form method="post">
        {% csrf_token %}
        {% if error_msg %}
            <p style="color: red;">{{ error_msg }}</p>
        {% endif %}
        <div class="genre-boxes">
            {% for genre in genres %}
                <label class="genre-label" data-genre-id="{{ genre.id }}">
                    <input type="checkbox" name="genres[]" value="{{ genre.id }}">
                    <div class="genre-box">{{ genre.name }}</div>
                </label>
            {% endfor %}
        </div>
        <label for="num_recommendations" align="center">Number of Recommendations:</label>
        
    <input type="number" name="num_recommendations" id="num_recommendations" value="10" min="1" max="50" align="center">
        <button type="submit">Generate!</button>
    </form>
    <form method="post" action="{% url 'movies:random_movie' %}">
        {% csrf_token %}
        <p align="center">Confused?</p>
        <button type="submit">Generate Random Movie</button>
    </form>
    <style>

        label[for="num_recommendations"],
        input[name="num_recommendations"] {
        display: block;
        margin: 0 auto;
        text-align: center;
        }
        body {
            background-color: #88b3c2;
        }
        .genre-boxes {
            display: flex;
            flex-wrap: wrap;
            margin: 20px 0;
        }
        .genre-label {
            display: flex;
            align-items: center;
            margin-right: 20px;
            margin-bottom: 20px;
            cursor: pointer;
        }
        .genre-box {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 120px;
            height: 60px;
            border: 2px solid #ccc;
            border-radius: 8px;
            font-size: 16px;
            font-weight: bold;
            color: #555;
            transition: background-color 0.3s ease;
            background-color: #c2cccc; 
        }
        input[type="checkbox"]:checked + .genre-box {
            background-color: #4CAF50;
            color: #fff;
        }
    </style>
{% endblock %}